[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH

; โปรเจกต์นี้ใช้ไลบรารีมาตรฐานที่มากับ Arduino core for ESP8266 อยู่แล้ว
; - Wire
; - ESP8266WiFi
; - ESP8266WebServer
