[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+

; ใช้ไลบรารีมาตรฐานที่มากับ Arduino core for ESP8266:
; - Wire.h สำหรับ I2C และ MPU6050
; - ESP8266WiFi.h สำหรับ Wi-Fi
; - ESP8266WebServer.h สำหรับหน้าเว็บปรับค่า PID
;
; โค้ดนี้จึงไม่ต้องเพิ่ม lib_deps ภายนอก

build_flags =
  -D PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH
